// Per-model token pricing so we can derive cost for tools that record tokens
// but not dollars (Claude transcripts and Codex rollouts carry usage, not cost).
// All rates are USD per million tokens.
//
// Two layers, vendored-first:
//
//   1. `pricing-data.json` — a committed snapshot of LiteLLM's community
//      pricing database (the source ccusage uses), regenerated by
//      `node scripts/update-pricing.mjs`. It carries EXPLICIT cache rates.
//   2. FALLBACK below — a small hand-maintained table used only for models the
//      snapshot lacks, or if the snapshot is missing entirely (offline clone).
//
// Hand-maintaining rates is what let `claude-opus-5` read $0 for weeks and left
// `claude-sonnet-5` 50% over its real intro rate. Prefer regenerating the
// snapshot over editing FALLBACK.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Cache multipliers for FALLBACK entries only. These match Anthropic's
// published ratios (reads ~0.1x input, 5-minute writes 1.25x input); the
// vendored snapshot supplies real per-model numbers instead of assuming them.
const CACHE_READ_MULTIPLIER = 0.1;
const CACHE_WRITE_MULTIPLIER = 1.25;
// Anthropic's 1-hour cache TTL bills writes at 2x input instead of 1.25x.
const CACHE_WRITE_1H_MULTIPLIER = 2;

const FALLBACK = {
  'claude-fable-5': { input: 10, output: 50 },
  'claude-mythos-5': { input: 10, output: 50 },
  'claude-opus-5': { input: 5, output: 25 },
  'claude-opus-4-8': { input: 5, output: 25 },
  'claude-opus-4-7': { input: 5, output: 25 },
  'claude-opus-4-6': { input: 5, output: 25 },
  'claude-opus-4-5': { input: 5, output: 25 },
  'claude-opus-4-1': { input: 15, output: 75 },
  'claude-opus-4': { input: 15, output: 75 },
  'claude-sonnet-5': { input: 3, output: 15 },
  'claude-sonnet-4-6': { input: 3, output: 15 },
  'claude-sonnet-4-5': { input: 3, output: 15 },
  'claude-sonnet-4': { input: 3, output: 15 },
  'claude-haiku-4-5': { input: 1, output: 5 },
  'gpt-5.6-sol': { input: 5, output: 30 },
  'gpt-5.6-terra': { input: 2.5, output: 15 },
  'gpt-5.6-luna': { input: 1, output: 6 },
  'gpt-5.5': { input: 5, output: 30 },
};

// Fill in cache rates so every entry has the same shape downstream, whatever
// layer it came from.
function withCacheRates(rate) {
  return {
    input: rate.input,
    output: rate.output,
    cacheRead: rate.cacheRead ?? rate.input * CACHE_READ_MULTIPLIER,
    cacheWrite: rate.cacheWrite ?? rate.input * CACHE_WRITE_MULTIPLIER,
    cacheWrite1h: rate.cacheWrite1h ?? rate.input * CACHE_WRITE_1H_MULTIPLIER,
  };
}

function loadVendored() {
  try {
    const raw = fs.readFileSync(path.join(__dirname, 'pricing-data.json'), 'utf8');
    return JSON.parse(raw).models || {};
  } catch {
    // No snapshot (fresh clone before the generator runs, or a read error) —
    // FALLBACK alone still produces correct numbers for the models we know.
    return {};
  }
}

// Vendored entries win over FALLBACK: the snapshot tracks intro pricing and
// rate changes that a hand-written table drifts away from.
const PRICING = {};
for (const [model, rate] of Object.entries(FALLBACK)) PRICING[model] = withCacheRates(rate);
for (const [model, rate] of Object.entries(loadVendored())) PRICING[model] = withCacheRates(rate);

// Keys are matched as prefixes (longest match wins) so dated snapshots like
// `claude-haiku-4-5-20251001` resolve to the `claude-haiku-4-5` entry.
export function priceForModel(model) {
  if (!model || model === 'unknown') return null;
  let best = null;
  let bestLen = -1;
  for (const key of Object.keys(PRICING)) {
    if (model.startsWith(key) && key.length > bestLen) {
      best = PRICING[key];
      bestLen = key.length;
    }
  }
  return best;
}

// Breaks a session's estimated cost into its four token components (USD), or
// null when the model isn't priceable. The four parts sum to estimateCost().
export function costBreakdown(session) {
  const rate = priceForModel(session.model);
  if (!rate) return null;
  // cacheWriteTokens is the TOTAL of both TTL tiers; cacheWrite1hTokens is the
  // 1-hour subset of it, billed at a higher rate. Sources that don't
  // distinguish tiers leave the subset at 0, so everything prices at the
  // 5-minute rate — the previous behaviour.
  const writeTotal = session.cacheWriteTokens || 0;
  const write1h = Math.min(session.cacheWrite1hTokens || 0, writeTotal);
  const write5m = writeTotal - write1h;
  return {
    input: ((session.inputTokens || 0) * rate.input) / 1_000_000,
    output: ((session.outputTokens || 0) * rate.output) / 1_000_000,
    cacheRead: ((session.cacheReadTokens || 0) * rate.cacheRead) / 1_000_000,
    cacheWrite: (write5m * rate.cacheWrite + write1h * rate.cacheWrite1h) / 1_000_000,
  };
}

// Returns the estimated cost in USD for a session's token usage, or null when
// the model isn't in the pricing table (caller keeps whatever cost it had).
export function estimateCost(session) {
  const parts = costBreakdown(session);
  if (!parts) return null;
  return parts.input + parts.output + parts.cacheRead + parts.cacheWrite;
}
