#!/usr/bin/env node
// Regenerate packages/ingest/src/pricing-data.json from LiteLLM's community
// pricing database — the same source ccusage uses.
//
// Why vendor instead of fetching at ingest time: ingest runs every few seconds
// from a watcher and must work offline. This writes a small, reviewable JSON
// snapshot that gets committed, so a pricing change shows up as a diff you can
// eyeball rather than silently moving the dashboard's numbers.
//
// Usage:  node scripts/update-pricing.mjs [--dry-run]
//
// Hand-maintaining rates is what let Opus 5 read $0 for weeks and Sonnet 5 sit
// 50% over its real intro rate. Re-run this when a new model family appears
// (the ingest WARNING tells you when) or every month or so.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SRC = 'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(__dirname, '..', 'packages', 'ingest', 'src', 'pricing-data.json');

// Only keep bare first-party ids for families we actually ingest. LiteLLM also
// carries provider-prefixed duplicates (`anthropic.claude-opus-5`,
// `azure/gpt-5.6-sol`, `bedrock/…`) whose rates differ by platform; our
// transcripts record the bare id, so those variants would never match and
// would only bloat the snapshot.
const KEEP = /^(claude|gpt|o[0-9]|deepseek|gemini|grok)[-.\w]*$/i;
const PER_MILLION = 1_000_000;

const round = n => (n == null ? null : Math.round(n * PER_MILLION * 1e6) / 1e6);

const res = await fetch(SRC);
if (!res.ok) throw new Error(`Failed to fetch LiteLLM pricing: HTTP ${res.status}`);
const raw = await res.json();

const out = {};
for (const [model, v] of Object.entries(raw)) {
  if (model === 'sample_spec' || !KEEP.test(model)) continue;
  if (v?.input_cost_per_token == null || v?.output_cost_per_token == null) continue;

  const entry = {
    input: round(v.input_cost_per_token),
    output: round(v.output_cost_per_token),
  };
  // Explicit cache rates when LiteLLM has them — strictly better than our
  // 0.1x / 1.25x heuristic, which is right for Anthropic but not universal.
  if (v.cache_read_input_token_cost != null) entry.cacheRead = round(v.cache_read_input_token_cost);
  if (v.cache_creation_input_token_cost != null) entry.cacheWrite = round(v.cache_creation_input_token_cost);
  // Anthropic bills a 1-hour cache write at 2x input vs 1.25x for the 5-minute
  // tier. Claude Code uses the 1h TTL heavily (55% of observed write tokens),
  // so folding both into one rate materially understates cost.
  if (v.cache_creation_input_token_cost_above_1hr != null) {
    entry.cacheWrite1h = round(v.cache_creation_input_token_cost_above_1hr);
  }
  out[model] = entry;
}

const sorted = Object.fromEntries(Object.keys(out).sort().map(k => [k, out[k]]));
const payload = {
  _source: SRC,
  _generated: new Date().toISOString(),
  _note: 'Generated by scripts/update-pricing.mjs. Rates are USD per million tokens. Do not hand-edit.',
  models: sorted,
};
const json = JSON.stringify(payload, null, 2) + '\n';

if (process.argv.includes('--dry-run')) {
  console.log(`${Object.keys(sorted).length} models (dry run, not written)`);
} else {
  fs.writeFileSync(OUT, json);
  console.log(`Wrote ${Object.keys(sorted).length} models to ${path.relative(process.cwd(), OUT)}`);
}
